name = "KeyVNA"
uuid = "78be0076-8ecc-45ef-a06f-667d575be7b6"
authors = ["Dominik Bergermann", "Nick Michaelis"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
